/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MyBidsRouteImport } from './routes/my-bids'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as EditListingRouteImport } from './routes/edit-listing'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingListingIdRouteImport } from './routes/listing.$listingId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBidsRoute = MyBidsRouteImport.update({
  id: '/my-bids',
  path: '/my-bids',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const EditListingRoute = EditListingRouteImport.update({
  id: '/edit-listing',
  path: '/edit-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingListingIdRoute = ListingListingIdRouteImport.update({
  id: '/listing/$listingId',
  path: '/listing/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/edit-listing': typeof EditListingRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-bids': typeof MyBidsRoute
  '/my-listings': typeof MyListingsRoute
  '/my-orders': typeof MyOrdersRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/listing/$listingId': typeof ListingListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/edit-listing': typeof EditListingRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-bids': typeof MyBidsRoute
  '/my-listings': typeof MyListingsRoute
  '/my-orders': typeof MyOrdersRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/listing/$listingId': typeof ListingListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/edit-listing': typeof EditListingRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-bids': typeof MyBidsRoute
  '/my-listings': typeof MyListingsRoute
  '/my-orders': typeof MyOrdersRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/listing/$listingId': typeof ListingListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions'
    | '/edit-listing'
    | '/inbox'
    | '/login'
    | '/my-bids'
    | '/my-listings'
    | '/my-orders'
    | '/orders'
    | '/settings'
    | '/listing/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/edit-listing'
    | '/inbox'
    | '/login'
    | '/my-bids'
    | '/my-listings'
    | '/my-orders'
    | '/orders'
    | '/settings'
    | '/listing/$listingId'
  id:
    | '__root__'
    | '/'
    | '/auctions'
    | '/edit-listing'
    | '/inbox'
    | '/login'
    | '/my-bids'
    | '/my-listings'
    | '/my-orders'
    | '/orders'
    | '/settings'
    | '/listing/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRoute: typeof AuctionsRoute
  EditListingRoute: typeof EditListingRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MyBidsRoute: typeof MyBidsRoute
  MyListingsRoute: typeof MyListingsRoute
  MyOrdersRoute: typeof MyOrdersRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  ListingListingIdRoute: typeof ListingListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bids': {
      id: '/my-bids'
      path: '/my-bids'
      fullPath: '/my-bids'
      preLoaderRoute: typeof MyBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-listing': {
      id: '/edit-listing'
      path: '/edit-listing'
      fullPath: '/edit-listing'
      preLoaderRoute: typeof EditListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$listingId': {
      id: '/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/listing/$listingId'
      preLoaderRoute: typeof ListingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRoute: AuctionsRoute,
  EditListingRoute: EditListingRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MyBidsRoute: MyBidsRoute,
  MyListingsRoute: MyListingsRoute,
  MyOrdersRoute: MyOrdersRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  ListingListingIdRoute: ListingListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
